language: node_js
node_js:
  - 12.13.0
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
env:
  - CXX=g++-4.8
sudo: required
before_script: yarn
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn test
